dist: xenial

language: go

# Specify which branches to build using a safelist
branches:
  only:
    - master

install:
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/Mr-six/hugo-theme-even.git themes/seven

script:
  # 运行hugo命令
  - hugo

after_script:
  # 部署
  - cd ./public
  - git init
  - git config user.name "$GIT_USER"
  - git config user.email "$EMAIL"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push -f --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master

env:
 global:
   # Github Pages
   - GH_REF: 'github.com/Mr-six/Mr-six.github.io.git'
